### ISSUE TITLE
Locked out of HR BLock Canada- really need to get my taxes done so...

### ISSUE THREAD

**Issue by katrinadunkley** [apereo/dotnet-cas-client#104]
CAS is unable to process this request: "500:Internal Server Error"

org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing ca.hrb.cas.mfa.web.flow.MultifactorAuthenticationVerifyTrustAction@16494888 in state 'mfaVerifyTrust' of flow 'mfa-security-question' -- action execution attributes were 'map['resolvedAuthenticationEvents' -> set[mfa-security-question]]'

**Comment by TheHokieCoder** [comment]
@katrinadunkley Your issue does not appear to be one related to this dotnet-cas-client project, especially since the exception that you have listed is one for the Spring framework, which is build on top of Java. This project is a CAS client for web applications built on the .NET framework. Also, your issue title mentions HR Block Canada, and that you're needing to get your taxes done, which would indicate that you are a customer of the web application...not a developer who is implementing/configuring the dotnet-cas-client in their application.

If I am wrong about this, please provide us with some more details about why you believe that this is a dotnet-cas-client issue. We will need details about how your web application is configured and laid out, what version of the client you are using, potentially a sanitized copy of your web.config so that we can see how you've configured the client, and then a description of the process you went through to encounter your error. If you provide these extra details, we'll be happy to try to help you resolve the issue!

**Comment by phantomtypist** [comment]
Almost positive this is just something wrong with HR Block Canada themselves.  It's a Java error like @TheHokieCoder said and this specific project does not use Java.
