### ISSUE TITLE
serverName set problem

### ISSUE THREAD

**Issue by CodeableChef** [apereo/dotnet-cas-client#107]
I have a problem, because my service domain is test.com, so I set the `serverName=test.com`, now I have two IPs under the domain , how can I visit the IP then redirect to this IP rather than the domain

**Comment by TheHokieCoder** [comment]
@CodeableChef would you please provide more detail on your web application's setup where you have two IP addresses for the same web application domain name, and why you have one where you want to kick off the authentication process but visit the other once authentication has been performed?

The only situation where I can think that this makes sense is when your web application is load-balanced, in which case your application would need a shared storage mechanism for maintaining the cache of valid service tickets so that all app servers behind the balancer can be aware of all authenticated users. Otherwise you will have a problem where server A knows about user X, but server B doesn't believe them to be a valid, authenticated user.

**Comment by TheHokieCoder** [comment]
Closing due to lack of response from the OP.
