### ISSUE TITLE
Support for Blazor Web Assembly?

### ISSUE THREAD

**Issue by bradybray** [apereo/dotnet-cas-client#126]
Hello;

Am I able to import and use the CAS client in Blazor Web Assembly? I get the impression the documentation is written for someone who is already quite familiar with development on ASP.NET Web Applications. I'm not too familiar and am wondering if I can import and setup the CAS client. 

Braden.

**Comment by TheHokieCoder** [comment]
@bradybray Unfortunately, no, you cannot use this CAS client with the Blazor framework. Blazor is built on the ASP.NET Core web framework, which is not supported by this client. In order to use CAS with Blazor, you will need to find a client that works with ASP.NET Core. Let us know if you have any further questions!
